USE QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

DECLARE @MACLB VARCHAR(5), @NAM INT, @VONG INT;
DECLARE @SOTRAN INT, @THANG INT, @HOA INT, @THUA INT, @HIEUSO VARCHAR(5), @DIEM INT;

-- CURSOR để duyệt dữ liệu từ VIEW hoặc nguồn tính toán trước
DECLARE CURSOR_BANGXH CURSOR FOR
SELECT 
    MACLB, NAM, VONG, COUNT(*) AS SOTRAN, 
    SUM(CASE 
        WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) > CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) 
        AND MACLB1 = MACLB THEN 1
        WHEN CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) > CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT)
        AND MACLB2 = MACLB THEN 1
        ELSE 0 END) AS THANG,
    SUM(CASE 
        WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) = CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 1
        ELSE 0 END) AS HOA,
    SUM(CASE 
        WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) < CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) 
        AND MACLB1 = MACLB THEN 1
        WHEN CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) < CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT)
        AND MACLB2 = MACLB THEN 1
        ELSE 0 END) AS THUA,
    CONCAT(
        SUM(CASE WHEN MACLB1 = MACLB THEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT)
                 WHEN MACLB2 = MACLB THEN CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) ELSE 0 END),
        '-',
        SUM(CASE WHEN MACLB1 = MACLB THEN CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT)
                 WHEN MACLB2 = MACLB THEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) ELSE 0 END)
    ) AS HIEUSO,
    SUM(CASE 
        WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) > CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) 
        AND MACLB1 = MACLB THEN 3
        WHEN CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) > CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT)
        AND MACLB2 = MACLB THEN 3
        WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) = CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 1
        ELSE 0 END) AS DIEM
FROM TRANDAU
JOIN CAULACBO CLB ON CLB.MACLB IN (MACLB1, MACLB2)
GROUP BY MACLB, NAM, VONG;

-- Mở CURSOR
OPEN CURSOR_BANGXH;

-- Duyệt qua từng dòng dữ liệu
FETCH NEXT FROM CURSOR_BANGXH INTO @MACLB, @NAM, @VONG, @SOTRAN, @THANG, @HOA, @THUA, @HIEUSO, @DIEM;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- Kiểm tra dữ liệu đã tồn tại trong bảng BANGXH
    IF EXISTS (SELECT 1 FROM BANGXH WHERE MACLB = @MACLB AND NAM = @NAM AND VONG = @VONG)
    BEGIN
        -- Nếu tồn tại, thực hiện UPDATE
        UPDATE BANGXH
        SET 
            SOTRAN = @SOTRAN,
            THANG = @THANG,
            HOA = @HOA,
            THUA = @THUA,
            HIEUSO = @HIEUSO,
            DIEM = @DIEM
        WHERE MACLB = @MACLB AND NAM = @NAM AND VONG = @VONG;
    END
    ELSE
    BEGIN
        -- Nếu chưa tồn tại, thực hiện INSERT
        INSERT INTO BANGXH (MACLB, NAM, VONG, SOTRAN, THANG, HOA, THUA, HIEUSO, DIEM, HANG)
        VALUES (@MACLB, @NAM, @VONG, @SOTRAN, @THANG, @HOA, @THUA, @HIEUSO, @DIEM, NULL);
    END;

    -- Lấy dòng tiếp theo
    FETCH NEXT FROM CURSOR_BANGXH INTO @MACLB, @NAM, @VONG, @SOTRAN, @THANG, @HOA, @THUA, @HIEUSO, @DIEM;
END;

-- Đóng và giải phóng CURSOR
CLOSE CURSOR_BANGXH;
DEALLOCATE CURSOR_BANGXH;

-------------------------------------------------

USE QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

CREATE PROCEDURE SP_UPDATE_BANGXH
AS
BEGIN
    DECLARE @MACLB VARCHAR(5), @NAM INT, @VONG INT;
    DECLARE @SOTRAN INT, @THANG INT, @HOA INT, @THUA INT, @HIEUSO VARCHAR(5), @DIEM INT;

    -- Khai báo CURSOR duyệt qua các dữ liệu từ bảng TRANDAU
    DECLARE CURSOR_BANGXH CURSOR FOR
    SELECT 
        MACLB, NAM, VONG, COUNT(*) AS SOTRAN, 
        SUM(CASE WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) > CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 1 ELSE 0 END) AS THANG,
        SUM(CASE WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) = CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 1 ELSE 0 END) AS HOA,
        SUM(CASE WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) < CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 1 ELSE 0 END) AS THUA,
        CONCAT(SUM(CASE WHEN MACLB1 = MACLB THEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) ELSE 0 END), '-', 
               SUM(CASE WHEN MACLB2 = MACLB THEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) ELSE 0 END)) AS HIEUSO,
        SUM(CASE WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) > CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 3
                 WHEN CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA) - 1) AS INT) = CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) AS INT) THEN 1 ELSE 0 END) AS DIEM
    FROM TRANDAU
    JOIN CAULACBO CLB ON CLB.MACLB = TRANDAU.MACLB1 OR CLB.MACLB = TRANDAU.MACLB2 -- Điều kiện JOIN chính xác
    GROUP BY MACLB, NAM, VONG;

    -- Mở CURSOR để duyệt qua dữ liệu
    OPEN CURSOR_BANGXH;

    FETCH NEXT FROM CURSOR_BANGXH INTO @MACLB, @NAM, @VONG, @SOTRAN, @THANG, @HOA, @THUA, @HIEUSO, @DIEM;

    -- Duyệt từng dòng trong CURSOR
    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Kiểm tra nếu dữ liệu đã tồn tại trong bảng BANGXH
        IF EXISTS (SELECT 1 FROM BANGXH WHERE MACLB = @MACLB AND NAM = @NAM AND VONG = @VONG)
        BEGIN
            -- Cập nhật dữ liệu nếu đã tồn tại
            UPDATE BANGXH 
            SET 
                SOTRAN = @SOTRAN, 
                THANG = @THANG, 
                HOA = @HOA, 
                THUA = @THUA, 
                HIEUSO = @HIEUSO, 
                DIEM = @DIEM
            WHERE MACLB = @MACLB AND NAM = @NAM AND VONG = @VONG;
        END
        ELSE
        BEGIN
            -- Chèn dữ liệu nếu chưa tồn tại
            INSERT INTO BANGXH (MACLB, NAM, VONG, SOTRAN, THANG, HOA, THUA, HIEUSO, DIEM, HANG)
            VALUES (@MACLB, @NAM, @VONG, @SOTRAN, @THANG, @HOA, @THUA, @HIEUSO, @DIEM, NULL);  -- Giả sử HANG sẽ tính sau
        END;

        -- Lấy dòng tiếp theo trong CURSOR
        FETCH NEXT FROM CURSOR_BANGXH INTO @MACLB, @NAM, @VONG, @SOTRAN, @THANG, @HOA, @THUA, @HIEUSO, @DIEM;
    END;

    -- Đóng và giải phóng CURSOR
    CLOSE CURSOR_BANGXH;
    DEALLOCATE CURSOR_BANGXH;
END;






