--58 Dùng lệnh print để in ra danh sách mã các cầu thủ, tên câu thủ, vị trí trên sân.
USE	QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

DECLARE CUR_BT1 CURSOR FOR
SELECT MACT, HOTEN, VITRI
FROM CAUTHU

OPEN CUR_BT1

DECLARE @MACT NUMERIC, @HOTEN NVARCHAR(50), @VITRI NVARCHAR(50);

FETCH NEXT FROM CUR_BT1 INTO @MACT, @HOTEN, @VITRI;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'MA CAU THU: ' + CAST(@MACT AS NVARCHAR) +
		', HO TEN: ' + @HOTEN +
		', VI TRI: ' + @VITRI

	FETCH NEXT FROM CUR_BT1 INTO @MACT, @HOTEN, @VITRI;
END

CLOSE CUR_BT1;
DEALLOCATE CUR_BT1;

--59
USE	QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

DECLARE CUR_BT2 CURSOR FOR
SELECT MACLB, TENCLB, TENSAN
FROM CAULACBO CLB

JOIN SANVD SVD ON CLB.MASAN = CLB.MASAN;

OPEN CUR_BT2;

DECLARE @MACLB NVARCHAR(50), @TENCLB NVARCHAR(50), @TENSANVD NVARCHAR(50);

FETCH NEXT FROM CUR_BT2 INTO @MACLB, @TENCLB, @TENSANVD;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'MACLB: ' + @MACLB + ', TENCLB: ' + @TENCLB + ', TENSANVD: ' + @TENSANVD; 
	
	FETCH NEXT FROM CUR_BT2 INTO @MACLB, @TENCLB, @TENSANVD;

END

CLOSE CUR_BT2
DEALLOCATE CURBT2
	
--60
USE QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

DECLARE CUR_BT3 CURSOR FOR
SELECT MACLB, COUNT(MACT) AS CNT
FROM CAUTHU
WHERE MAQG <> 'VN'
GROUP BY MACLB;

OPEN CUR_BT3;

DECLARE @MACLB NVARCHAR(50), @CNT INT;

FETCH NEXT FROM CUR_BT3 INTO @MACLB, @CNT;

WHILE @@FETCH_STATUS = 0
BEGIN 
	PRINT 'MA CLB: ' + @MACLB + 
		', SL CAUTHU NC NGOAI: ' + CAST(@CNT AS NVARCHAR);
	FETCH NEXT FROM CUR_BT3 INTO @MACLB, @CNT;
END

CLOSE CUR_BT3 
DEALLOCATE CUR_BT3	

--61
USE QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

DECLARE CUR_BT4 CURSOR FOR
SELECT CLB.MACLB, COUNT(HLVCLB.MAHLV) AS CNT
FROM CAULACBO CLB

JOIN HLV_CLB HLVCLB ON HLVCLB.MACLB = CLB.MACLB
JOIN HUANLUYENVIEN HLV ON HLVCLB.MAHLV = HLV.MAHLV

WHERE MAQG <> 'VN' 
GROUP BY CLB.MACLB

OPEN CUR_BT4;

DECLARE @MACLB NVARCHAR(50), @CNT INT;

FETCH NEXT FROM CUR_BT4 INTO @MACLB, @CNT

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'CAU LAC BO: ' + @MACLB + 
		', SO LUONG HLV NN: ' + CAST(@CNT AS NVARCHAR);
	FETCH NEXT FROM CUR_BT4 INTO @MACLB, @CNT;
END

CLOSE CUR_BT4
DEALLOCATE CUR_BT4
	
--62A
USE	QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

CREATE VIEW VIEW62A AS
SELECT
	TD.MACLB1 AS MACL1,
	TD.MACLB2 AS MACLB2,
	COUNT (*) AS SOTRANHOA

	FROM TRANDAU TD

	WHERE KETQUA LIKE '%-%'
		AND LEFT (KETQUA, CHARINDEX('-', KETQUA) - 1)
			= RIGHT (KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA)) 
	GROUP BY TD.MACLB1, td.MACLB2;

SELECT * FROM VIEW62A

--62B
USE QUAN_LY_GIAI_BONG_DA_V_LEAGUE
GO

CREATE VIEW VIEW62B AS
SELECT 
    CLB.MACLB, -- Mã câu lạc bộ
    TD.NAM,    -- Năm
    TD.VONG,   -- Vòng đấu

    -- Tổng điểm (chỉ tính điểm thắng)
    SUM(
        CASE 
            WHEN (TD.MACLB1 = CLB.MACLB AND 
                  CAST(LEFT(TD.KETQUA, CHARINDEX('-', TD.KETQUA) - 1) AS INT) >
                  CAST(RIGHT(TD.KETQUA, LEN(TD.KETQUA) - CHARINDEX('-', TD.KETQUA)) AS INT))
            OR 
                 (TD.MACLB2 = CLB.MACLB AND 
                  CAST(RIGHT(TD.KETQUA, LEN(TD.KETQUA) - CHARINDEX('-', TD.KETQUA)) AS INT) >
                  CAST(LEFT(TD.KETQUA, CHARINDEX('-', TD.KETQUA) - 1) AS INT))
            THEN 1 -- Chỉ tính điểm khi thắng
            ELSE 0 -- Không tính điểm cho thua hoặc hòa
        END
    ) AS TONG_DIEM,

    -- Tổng bàn thắng
    SUM(
        CASE 
            WHEN TD.MACLB1 = CLB.MACLB THEN CAST(LEFT(TD.KETQUA, CHARINDEX('-', TD.KETQUA) - 1) AS INT)
            WHEN TD.MACLB2 = CLB.MACLB THEN CAST(RIGHT(TD.KETQUA, LEN(TD.KETQUA) - CHARINDEX('-', TD.KETQUA)) AS INT)
            ELSE 0
        END
    ) AS TONG_BANTHANG,

    -- Tổng bàn thua
    SUM(
        CASE 
            WHEN TD.MACLB1 = CLB.MACLB THEN CAST(RIGHT(TD.KETQUA, LEN(TD.KETQUA) - CHARINDEX('-', TD.KETQUA)) AS INT)
            WHEN TD.MACLB2 = CLB.MACLB THEN CAST(LEFT(TD.KETQUA, CHARINDEX('-', TD.KETQUA) - 1) AS INT)
            ELSE 0
        END
    ) AS TONG_BANTHUA,

    -- Hiệu số
    SUM(
        CASE 
            WHEN TD.MACLB1 = CLB.MACLB THEN CAST(LEFT(TD.KETQUA, CHARINDEX('-', TD.KETQUA) - 1) AS INT) -
                                           CAST(RIGHT(TD.KETQUA, LEN(TD.KETQUA) - CHARINDEX('-', TD.KETQUA)) AS INT)
            WHEN TD.MACLB2 = CLB.MACLB THEN CAST(RIGHT(TD.KETQUA, LEN(TD.KETQUA) - CHARINDEX('-', TD.KETQUA)) AS INT) -
                                           CAST(LEFT(TD.KETQUA, CHARINDEX('-', TD.KETQUA) - 1) AS INT)
            ELSE 0
        END
    ) AS HIEU_SO

FROM TRANDAU TD
JOIN CAULACBO CLB ON CLB.MACLB IN (TD.MACLB1, TD.MACLB2)
GROUP BY CLB.MACLB, TD.NAM, TD.VONG

SELECT * 
FROM VIEW62B
ORDER BY TONG_DIEM DESC, HIEU_SO DESC, TONG_BANTHANG DESC, TONG_BANTHUA ASC;

--62C
