USE [dbXe]
GO

ALTER TABLE TAIXE
ADD SOBANGLAI INT DEFAULT 0;
GO


USE [dbXe]
GO

CREATE TRIGGER TRG_CAU3
ON BANGLAI
AFTER INSERT, DELETE, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM INSERTED)
    BEGIN
        UPDATE TAIXE
        SET SOBANGLAI = (
            SELECT COUNT(*)
            FROM BANGLAI BL
            WHERE BL.MATAIXE = TAIXE.MATAIXE
        )
        WHERE MATAIXE IN (SELECT MATAIXE FROM INSERTED);
    END

    IF EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        UPDATE TAIXE
        SET SOBANGLAI = (
            SELECT COUNT(*)
            FROM BANGLAI BL
            WHERE BL.MATAIXE = TAIXE.MATAIXE
        )
        WHERE MATAIXE IN (SELECT MATAIXE FROM DELETED);
    END
END;
GO
