USE [dbXe]
GO

CREATE PROCEDURE CAU1 
	@LOAIGPLX NVARCHAR(50)
AS
	
BEGIN 
	DECLARE @MABANGLAI NVARCHAR(4)
	DECLARE @NGAYCAP DATE
	DECLARE @MATAIXE NVARCHAR(4)
	DECLARE @HOTENTAIXE NVARCHAR(50)
	DECLARE @NGAYSINH DATE
	DECLARE @DIACHI NVARCHAR(100)
	
	 DECLARE CUR_CAU1 CURSOR FOR
    SELECT 
        BL.MABANGLAI, BL.MATAIXE, BL.NGAYCAP, 
			TX.HOTENTAIXE, TX.NGAYSINH, TX.DIACHI
    FROM 
        BANGLAI BL
    JOIN 
        TAIXE TX ON BL.MATAIXE = TX.MATAIXE
    WHERE 
        BL.LOAIGPLX = @LOAIGPLX AND YEAR(BL.NGAYCAP) = 2024

    OPEN CUR_CAU1

    FETCH NEXT FROM CUR_CAU1 INTO @MABANGLAI, @MATAIXE, @NGAYCAP, @HOTENTAIXE, @NGAYSINH, @DIACHI

    WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT N'Mã Bằng Lái: ' + @MABANGLAI + N', Mã Tài Xế: ' + @MATAIXE + 
              N', Ngày Cấp: ' + CONVERT(VARCHAR, @NGAYCAP, 103) +
              N', Họ Tên: ' + @HOTENTAIXE + 
              N', Ngày Sinh: ' + CONVERT(VARCHAR, @NGAYSINH, 103) +
              N', Địa Chỉ: ' + @DIACHI

        FETCH NEXT FROM CUR_CAU1 INTO @MABANGLAI, @MATAIXE, @NGAYCAP, @HOTENTAIXE, @NGAYSINH, @DIACHI
    END

    CLOSE CUR_CAU1
    DEALLOCATE CUR_CAU1
END
GO
